name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build executables
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            pyinstaller --onefile main.py
          else
            pyinstaller --onefile main.py
        shell: bash

      - name: Archive executable
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: executable-linux
          path: dist/DupliPicFinder

      - name: Archive executable
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: executable-windows
          path: dist/DupliPicFinder.exe

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Parse version from setup.py
        id: get_version
        run: |
          VERSION=$(python setup.py --version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Download Linux executable
        uses: actions/download-artifact@v2
        with:
          name: executable-linux
          path: ./dist

      - name: Download Windows executable
        uses: actions/download-artifact@v2
        with:
          name: executable-windows
          path: ./dist

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Linux executable to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/DupliPicFinder
          asset_name: DupliPicFinder
          asset_content_type: application/octet-stream

      - name: Upload Windows executable to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/DupliPicFinder.exe
          asset_name: DupliPicFinder.exe
          asset_content_type: application/octet-stream
