name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    name: Build Linux executable
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onedir --name DupliPicFinder src/main.py

      - name: Rename and Zip Linux executable
        run: |
          cd dist
          mv DupliPicFinder DupliPicFinder-linux
          zip -r DupliPicFinder-linux.zip DupliPicFinder-linux

      - name: Archive Linux executable zip
        uses: actions/upload-artifact@v4
        with:
          name: executable-linux
          path: dist/DupliPicFinder-linux.zip

  build-windows:
    name: Build Windows executable
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onedir --noconsole --name DupliPicFinder src/main.py --target-arch x86_64 --clean

      - name: Rename and Zip Windows executable
        run: |
          powershell Rename-Item -Path dist\DupliPicFinder -NewName DupliPicFinder-windows-x64
          powershell Compress-Archive -Path dist\DupliPicFinder-windows-x64 -DestinationPath dist\DupliPicFinder-windows-x64.zip

      - name: Archive Windows executable zip
        uses: actions/upload-artifact@v4
        with:
          name: executable-windows
          path: dist/DupliPicFinder-windows-x64.zip

  release:
    name: Create Release
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Parse version from setup.py
        id: get_version
        run: |
          VERSION=$(python setup.py --version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Download Linux executable zip
        uses: actions/download-artifact@v4
        with:
          name: executable-linux
          path: ./dist

      - name: Download Windows executable zip
        uses: actions/download-artifact@v4
        with:
          name: executable-windows
          path: ./dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./dist/DupliPicFinder-linux.zip
            ./dist/DupliPicFinder-windows-x64.zip
          draft: false
          prerelease: false
          tag_name: v${{ env.VERSION }}
          name: DupliPicFinder v${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
