# .github/workflows/linux-build.yml
name: Build and Release Ubuntu Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile src/main.py

      - name: Upload Ubuntu executable
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-executable
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version from setup.py
        id: get_version
        run: |
          version=$(python -c "import setuptools; print(setuptools.__version__)")
          echo "VERSION=${version}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v3
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Ubuntu executable
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/main
          asset_name: main
          asset_content_type: application/octet-stream
